service: life-api
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  role: arn:aws:iam::929828279562:role/QuaseAdmin
functions:
  # Users
  getUsers:
    handler: functions/users.getUsers
    events:
      - http: GET users
        cors: true
  getUserById:
    handler: functions/users.getUserById
    events:
      - http: GET users/{id}
        cors: true
  createUser:
      handler: functions/users.createUser
      events:
        - http: POST users
          cors: true
  deleteUser:
      handler: functions/users.deleteUser
      events:
        - http: DELETE users/{id}
          cors: true
  # Clients
  getClients:
    handler: functions/clients.getClients
    events:
      - http: GET clients
        cors: true
  getClientById:
    handler: functions/clients.getClientById
    events:
      - http: GET clients/{id}
        cors: true
  createClient:
    handler: functions/clients.createClient
    events:
      - http: POST clients
        cors: true
  deleteClient:
    handler: functions/clients.deleteClient
    events:
      - http: DELETE clients/{id}
        cors: true
  # Flavors
  getFlavors:
    handler: functions/flavors.getFlavors
    events:
      - http: GET flavors
        cors: true
  createFlavor:
    handler: functions/flavors.createFlavor
    events:
      - http: POST flavors
        cors: true
  getFlavorById:
    handler: functions/flavors.getFlavorById
    events:
      - http: GET flavors/{id}
        cors: true
  deleteFlavor:
    handler: functions/flavors.deleteFlavor
    events:
      - http: DELETE flavors/{id}
        cors: true


  